#
# Makefile
#
# Computer Science 50
# Problem Set 3
#

compare-0: compare-0.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o compare-0 compare-0.c -lcs50 -lm

compare-1: compare-1.c
		clang -ggdb3 -O0 -std=c11 -Wall -Werror -o compare-1 compare-1.c -lcs50 -lm
