copy-0: copy-0
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o copy-0 copy-0.c -lcs50 -lm
copy-1: copy-1
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o copy-1 copy-1.c -lcs50 -lm
copy-2: copy-2
		clang -ggdb3 -O0 -std=c11 -Wall -Werror -o copy-2 copy-2.c -lcs50 -lm
