sigma-0: sigma-0.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o sigma-0 sigma-0.c -lcs50 -lm

sigma-1: sigma-1.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o sigma-1 sigma-1.c -lcs50 -lm

clean:
	rm -f *.o a.out core fifteen log.txt
