structs-0: structs-0.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o structs-0 structs-0.c -lcs50 -lm

structs-1: structs-1.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o structs-1 structs-1.c -lcs50 -lm
